### ISSUE TITLE
一致说无法加载。js的资源

### ISSUE THREAD

**Issue by javamr123** [lonerchen/flutter_web3view#1]
Unable to load asset

**Comment by lonerchen** [comment]
哪个平台上会有这个报错

**Comment by javamr123** [comment]
安卓，就是正常跑你的demo，我的邮箱Java_mr@163.com,方便加您的qq或者微信吗？您可以把您的号发送到这个邮箱，向大佬学习，谢谢

**Comment by lonerchen** [comment]
没问题，一起交流

**Comment by mekery** [comment]
@Javamr123 @lonerchen 
这个问题解决了吗？能发个微信号给我吗，学习下。我邮箱是46499457@qq.com，谢谢
